/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-06-02 03:10:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class company_005f6_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Dashboard Template · Bootstrap v5.0</title>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/dashboard/\"> -->\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"./css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- fontawesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("p {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("\tfont-size: 1.125rem;\r\n");
      out.write("\ttext-anchor: middle;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebarMenu a:hover {\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("\t.bd-placeholder-img-lg {\r\n");
      out.write("\t\tfont-size: 3.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header\r\n");
      out.write("\t\tclass=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\r\n");
      out.write("\t\t<a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3\" href=\"#\">Company\r\n");
      out.write("\t\t\tname</a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler position-absolute d-md-none collapsed\"\r\n");
      out.write("\t\t\ttype=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#sidebarMenu\"\r\n");
      out.write("\t\t\taria-controls=\"sidebarMenu\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<input class=\"form-control form-control-dark w-100\" type=\"text\"\r\n");
      out.write("\t\t\tplaceholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav px-3\">\r\n");
      out.write("\t\t\t<li class=\"nav-item text-nowrap\"><a class=\"nav-link\" href=\"#\">Sign\r\n");
      out.write("\t\t\t\t\tout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div></div>\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\r\n");
      out.write("\t\t\t\t<div class=\"position-sticky pt-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" aria-current=\"page\" href=\"./dashboard.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-tachometer-alt\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\tDashboard\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"./login_1.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-sign-in-alt\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t會員\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"./Login.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-funnel-dollar\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t下單\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"./Post_3.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"me-1\"><i class=\"far fa-comment-dots\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t討論\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"./Buy_4.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-dice-d20\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t抽籤\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"./CourseManagement5.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-clipboard-list\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t課程\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link active\" href=\"./company_6.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-building\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t公司資料\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 內容 -->\r\n");
      out.write("\t\t\t<main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\">\r\n");
      out.write("\t\t\t\t");
      jdbc_6.TableBean_6 TableBean_6 = null;
      TableBean_6 = (jdbc_6.TableBean_6) _jspx_page_context.getAttribute("TableBean_6", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (TableBean_6 == null){
        TableBean_6 = new jdbc_6.TableBean_6();
        _jspx_page_context.setAttribute("TableBean_6", TableBean_6, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<form action=\"./MainServlet_6\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item_CRUD mt-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Basic radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"whichOne\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"select\" autocomplete=\"off\" value=\"select\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-outline-primary\" for=\"select\">查詢資料</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"radio\" class=\"btn-check\" name=\"whichOne\" id=\"insert\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautocomplete=\"off\" value=\"insert\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-outline-primary\" for=\"insert\">新增資料</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"radio\" class=\"btn-check\" name=\"whichOne\" id=\"update\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautocomplete=\"off\" value=\"update\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-outline-primary\" for=\"update\">更新資料</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"radio\" class=\"btn-check\" name=\"whichOne\" id=\"delete\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautocomplete=\"off\" value=\"delete\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-outline-primary\" for=\"delete\">刪除資料</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content mt-5 col-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col mb-5\" id=\"searchData\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"\" class=\"form-label\">查詢資料</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"search\" placeholder=\"統一編號\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"search_business_NO\" onfocus=\"this.placeholder=''\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"this.placeholder='統一編號'\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mb-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>查詢結果:</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p id=\"answer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"");
      out.print(request.getAttribute("result"));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"formData\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row row-cols-1 row-cols-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"\" class=\"form-label\">統一編號</label> \r\n");
      out.write("                    <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"business_Accounting_NO\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"business_Accounting_NO\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbc_6.TableBean_6)_jspx_page_context.findAttribute("TableBean_6")).getBusiness_Accounting_NO())));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"\" class=\"form-label\">公司名稱</label> \r\n");
      out.write("                    <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"company_Name\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"company_Name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbc_6.TableBean_6)_jspx_page_context.findAttribute("TableBean_6")).getCompany_Name())));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"\" class=\"form-label\">資本總額(登記資本額)</label> \r\n");
      out.write("                    <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"capital_Stock_Amount\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"capital_Stock_Amount\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbc_6.TableBean_6)_jspx_page_context.findAttribute("TableBean_6")).getS_capital_Stock_Amount())));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"\" class=\"form-label\">代表人姓名</label> \r\n");
      out.write("                    <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"responsible_Name\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"responsible_Name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbc_6.TableBean_6)_jspx_page_context.findAttribute("TableBean_6")).getResponsible_Name())));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row row-cols-1 row-cols-lg-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col mb-3\">\r\n");
      out.write("                  <label for=\"\" class=\"form-label\">公司所在地</label>\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" id=\"company_Location\" placeholder=\"\" name=\"company_Location\"\r\n");
      out.write("                    value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbc_6.TableBean_6)_jspx_page_context.findAttribute("TableBean_6")).getCompany_Location())));
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id=\"submit\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"./js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"./js/jquery-3.6.0.js\"></script>\r\n");
      out.write("\t<script src=\"./js/company_6.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("      $(function () {\r\n");
      out.write("\t\t$('#formData').hide()  \r\n");
      out.write("        $('#");
      out.print(request.getAttribute("checkOption"));
      out.write("').prop('checked', true)\r\n");
      out.write("\r\n");
      out.write("        // insert、update 失敗\r\n");
      out.write("        if (\"");
      out.print(request.getAttribute("beanErr"));
      out.write("\" == \"error\") {\r\n");
      out.write("\t\t\t\t$('#formData').show()\r\n");
      out.write("        \t\t$('#searchData').hide()\r\n");
      out.write("\t\t\t}else if(\"");
      out.print(request.getAttribute("beanErr"));
      out.write("\" == \"correct\"){\r\n");
      out.write("\t\t\t\t$('#formData').hide()\r\n");
      out.write("\t\t\t\t$('#searchData').hide()\r\n");
      out.write("      \t\t}else if(\"");
      out.print(request.getAttribute("beanErr"));
      out.write("\" == \"correctData\"){\r\n");
      out.write("\t\t\t\t$('#formData').show()\r\n");
      out.write("        \t\t$('#searchData').hide()\r\n");
      out.write("      \t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
