/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-12 14:06:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import bean_5.Course;
import java.util.List;

public final class CourseDataSet5_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("bean_5.Course");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      bean_5.Course course = null;
      synchronized (session) {
        course = (bean_5.Course) _jspx_page_context.getAttribute("course", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (course == null){
          course = new bean_5.Course();
          _jspx_page_context.setAttribute("course", course, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<head>\r\n");
      out.write("\t\t\t\t\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t\t\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t\t\t\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t\t\t\t\t<meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("\t\t\t\t\t\t<meta name=\"generator\" content=\"Hugo 0.82.0\">\r\n");
      out.write("\t\t\t\t\t\t<title>CourseManagement</title>\r\n");
      out.write("\t\t\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css\">\r\n");
      out.write("\t\t\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./chibon_5/style.css\">\r\n");
      out.write("\t\t\t\t\t\t<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<link href=\"./css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t\t\t\t<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<style>\r\n");
      out.write("\t\t\t\t\t\t\t.bd-placeholder-img {\r\n");
      out.write("\t\t\t\t\t\t\t  font-size: 1.125rem;\r\n");
      out.write("\t\t\t\t\t\t\t  text-anchor: middle;\r\n");
      out.write("\t\t\t\t\t\t\t  -webkit-user-select: none;\r\n");
      out.write("\t\t\t\t\t\t\t  -moz-user-select: none;\r\n");
      out.write("\t\t\t\t\t\t\t  user-select: none;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t#sidebarMenu a:hover {\r\n");
      out.write("\t\t\t\t\t\t\t  color: blue;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t@media (min-width: 768px) {\r\n");
      out.write("\t\t\t\t\t\t\t  .bd-placeholder-img-lg {\r\n");
      out.write("\t\t\t\t\t\t\t\tfont-size: 3.5rem;\r\n");
      out.write("\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t  </style>\r\n");
      out.write("\t\t\t\t\t</head>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<body>\r\n");
      out.write("\t\t\t\t\t\t<header class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3\" href=\"#\">Company name</a>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t  data-bs-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t  <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control form-control-dark w-100\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"navbar-nav px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li class=\"nav-item text-nowrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"#\">Sign out</a>\r\n");
      out.write("\t\t\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t  </header>\r\n");
      out.write("\t\t\t\t\t\t  <div></div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t  <nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\r\n");
      out.write("\t\t\t\t<div class=\"position-sticky pt-3\">\r\n");
      out.write("\t\t\t\t  <ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"nav-link\" aria-current=\"page\" href=\"./dashboard.html\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-tachometer-alt\"></i></span>\r\n");
      out.write("\t\t\t\t\t\tDashboard\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"nav-link\" href=\"./login_1.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-sign-in-alt\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t會員\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"nav-link\" href=\"./Login.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-funnel-dollar\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t下單\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"nav-link\" href=\"./Post_3.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"me-1\"><i class=\"far fa-comment-dots\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t討論\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"nav-link\" href=\"./Buy_4.html\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-dice-d20\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t抽籤\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"nav-link active\" href=\"./CourseManagement5.html\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-clipboard-list\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t課程\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"nav-link\" href=\"./company_6.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"me-1\"><i class=\"fas fa-building\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t公司資料\r\n");
      out.write("\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  <!-- 內容 -->\r\n");
      out.write("\t\t\t\t\t\t\t  <main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<button onclick=\"setActionCodeInsert();\" id=\"insert\" class=\"btn btn-info btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#myModal\">新增</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<table id=\"table_id\" class=\"display\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>課程編號</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>講師姓名</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>課程主題</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>場次日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>上課時間</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>收費</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>名額</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>分類</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>授課方式</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>地區</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>備註</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 List<Course> courseList = (List<Course>) session.getAttribute("Courses");
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 if(courseList !=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!--<c:forEach var=\"item\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 for(Course c:courseList){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"operation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button onclick=\"setActionCodeUpdate(this);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-info btn-sm update\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#myModal\">修改</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button onclick=\"setActionCodeDelete(this);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-info btn-sm delete\">刪除</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.courseID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.teacherName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.courseOutline}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.courseDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.courseTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quota}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.classification}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.teachingMethod}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.area}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.comment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"courseIdSet\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getCourseID() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getTeacherName() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getCourseOutline() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getCourseDate() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getCourseTime() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getFee().setScale(0) );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getQuota() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getClassification() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getTeachingMethod() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getArea() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( c.getComment() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!--</c:forEach>-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 模态框（Modal） -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">新增/修改視窗</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--在这里添加一些文本-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"./CourseServlet\" method=\"post\" onsubmit=\"return check();\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table id=\"insertOrAlter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>課程編號</label> <input type=\"text\" name=\"courseID\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"課程編號\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>講師姓名</label> <input type=\"text\" name=\"teacherName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"講師姓名\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>課程大綱</label><input type=\"text\" name=\"courseOutline\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"課程大綱\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>場次日期</label> <input type=\"date\" name=\"courseDate\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"場次日期\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>上課時間</label> <input type=\"text\" name=\"courseTime\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"上課時間\" pattern=\"([01]?[0-9]|2[0-3]):[0-5][0-9]\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"24h\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>費用</label><input type=\"text\" name=\"fee\" placeholder=\"費用\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>開課名額</label><input type=\"text\" name=\"quota\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"開課名額\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>分類</label><input type=\"text\" name=\"classification\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"分類\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>授課方式</label> <input type=\"text\" name=\"teachingMethod\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"授課方式\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>上課地區</label> <input type=\"text\" name=\"area\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"上課地區\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label>備註</label><input type=\"text\" name=\"comment\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"備註\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"actionCode1\" type=\"hidden\" name=\"actionCode\" value=\"null\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">關閉</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">送出</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /.modal-content -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /.modal -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<form id=\"FormSubmiter\" action=\"./CourseServlet\" method=\"post\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"actionCode2\" type=\"hidden\" name=\"actionCode\" value=\"null\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"deleteCourseID\" value=\"null\" id=\"deletecourseID\">;\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"autoSubmiter\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  <script src=\"./js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t\t\t  <script type=\"text/javascript\" charset=\"utf8\" src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" charset=\"utf8\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" charset=\"utf8\" src=\"https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" charset=\"utf8\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" charset=\"utf8\" src=\"./chibon_5/main.js\"></script>\r\n");
      out.write("\t\t\t\t\t</body>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
