/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-06-02 03:10:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("  <meta name=\"generator\" content=\"Hugo 0.82.0\">\r\n");
      out.write("  <title>Dashboard Template · Bootstrap v5.0</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/dashboard/\"> -->\r\n");
      out.write("   <!-- Bootstrap core CSS -->\r\n");
      out.write("   <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"./css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- fontawesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    .bd-placeholder-img {\r\n");
      out.write("      font-size: 1.125rem;\r\n");
      out.write("      text-anchor: middle;\r\n");
      out.write("      -webkit-user-select: none;\r\n");
      out.write("      -moz-user-select: none;\r\n");
      out.write("      user-select: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebarMenu a:hover {\r\n");
      out.write("      color: blue;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (min-width: 768px) {\r\n");
      out.write("      .bd-placeholder-img-lg {\r\n");
      out.write("        font-size: 3.5rem;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <header class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\r\n");
      out.write("    <a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3\" href=\"#\">Company name</a>\r\n");
      out.write("    <button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("      data-bs-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <input class=\"form-control form-control-dark w-100\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("    <ul class=\"navbar-nav px-3\">\r\n");
      out.write("      <li class=\"nav-item text-nowrap\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">Sign out</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </header>\r\n");
      out.write("  <div></div>\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\r\n");
      out.write("        <div class=\"position-sticky pt-3\">\r\n");
      out.write("          <ul class=\"nav flex-column\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" aria-current=\"page\" href=\"./dashboard.html\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-tachometer-alt\"></i></span>\r\n");
      out.write("                Dashboard\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./login_1.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-sign-in-alt\"></i></span>\r\n");
      out.write("                會員\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" href=\"./Login.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-funnel-dollar\"></i></span>\r\n");
      out.write("                下單\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./Post_3.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"far fa-comment-dots\"></i></span>\r\n");
      out.write("                討論\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./Buy_4.html\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-dice-d20\"></i></span>\r\n");
      out.write("                抽籤\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./CourseManagement5.html\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-clipboard-list\"></i></span>\r\n");
      out.write("                課程\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./company_6.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-building\"></i></span>\r\n");
      out.write("                公司資料\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      <!-- 內容 -->\r\n");
      out.write("      <main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\">\r\n");
      out.write("        <form action=\"./Login\"  method=\"POST\">\r\n");
      out.write("    \r\n");
      out.write("          <fieldset>\r\n");
      out.write("          <legend>測試帳號申請</legend>\r\n");
      out.write("           <div>\r\n");
      out.write("             <label for=\"stock_ID\">證券測試戶:</label>\r\n");
      out.write("            <input type=\"text\" id=\"stock_ID\" name=\"stock_ID\">\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div>\r\n");
      out.write("             <label for=\"user_account\">使用者帳號:</label>\r\n");
      out.write("            <input type=\"text\" id=\"user_account\" name=\"user_account\">\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div>\r\n");
      out.write("             <label for=\"user_password\">使用者密碼:</label>\r\n");
      out.write("            <input type=\"text\" id=\"user_password\" name=\"user_password\">\r\n");
      out.write("          </div>\r\n");
      out.write("          </fieldset>\r\n");
      out.write("           \r\n");
      out.write("          <div>\r\n");
      out.write("             <input  type=\"submit\" value=\"送出申請\">\r\n");
      out.write("          </div>\r\n");
      out.write("       \r\n");
      out.write("          </form>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"./js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
