/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-12 13:40:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("  <meta name=\"generator\" content=\"Hugo 0.82.0\">\n");
      out.write("  <title>Dashboard Template · Bootstrap v5.0</title>\n");
      out.write("\n");
      out.write("  <!-- <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/dashboard/\"> -->\n");
      out.write("   <!-- Bootstrap core CSS -->\n");
      out.write("   <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"./css/dashboard.css\" rel=\"stylesheet\">\n");
      out.write("  <!-- fontawesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"./Order_style.css\">\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <style>\n");
      out.write("    .bd-placeholder-img {\n");
      out.write("      font-size: 1.125rem;\n");
      out.write("      text-anchor: middle;\n");
      out.write("      -webkit-user-select: none;\n");
      out.write("      -moz-user-select: none;\n");
      out.write("      user-select: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #sidebarMenu a:hover {\n");
      out.write("      color: blue;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @media (min-width: 768px) {\n");
      out.write("      .bd-placeholder-img-lg {\n");
      out.write("        font-size: 3.5rem;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("     <!-- 測試auto -->\n");
      out.write("    *{\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("    }\n");
      out.write("    .content{\n");
      out.write("      height: 100vh;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("    }\n");
      out.write("    .content .header{\n");
      out.write("      height: 50px;\n");
      out.write("      line-height: 50px;\n");
      out.write("      font-size: 26px;\n");
      out.write("      text-align: center;\n");
      out.write("      border-bottom: 2px solid red;\n");
      out.write("    }\n");
      out.write("    .content iframe{\n");
      out.write("      flex: 1;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("  \n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <header class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\n");
      out.write("    <a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3\" href=\"#\">Company name</a>\n");
      out.write("    <button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("      data-bs-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <input class=\"form-control form-control-dark w-100\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("    <ul class=\"navbar-nav px-3\">\n");
      out.write("      <li class=\"nav-item text-nowrap\">\n");
      out.write("        <a class=\"nav-link\" href=\"#\">Sign out</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("  </header>\n");
      out.write("  <div></div>\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n");
      out.write("        <div class=\"position-sticky pt-3\">\n");
      out.write("          <ul class=\"nav flex-column\">\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" aria-current=\"page\" href=\"./dashboard.html\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-tachometer-alt\"></i></span>\n");
      out.write("                Dashboard\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./login_1.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-sign-in-alt\"></i></span>\n");
      out.write("                會員\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link active\" href=\"./Login.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-funnel-dollar\"></i></span>\n");
      out.write("                下單\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./Post_3.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"far fa-comment-dots\"></i></span>\n");
      out.write("                討論\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./Buy_4.html\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-dice-d20\"></i></span>\n");
      out.write("                抽籤\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./CourseManagement5.html\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-clipboard-list\"></i></span>\n");
      out.write("                課程\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./company_6.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-building\"></i></span>\n");
      out.write("                公司資料\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("\n");
      out.write("      <!-- 內容 -->\n");
      out.write("      <main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\">\n");
      out.write("        ");
 
        String stock_ID      = (String) session.getAttribute("stock_ID");
      String user_account  = (String) session.getAttribute("user_account");
      
      out.write("\n");
      out.write("      <h2 id=\"test\">Hi,");
      out.print(user_account);
      out.write(",歡迎使用快速下單!</h2>\n");
      out.write("  \n");
      out.write("      <span>\n");
      out.write("          <iframe id=\"Kline\" src=\"https://s.yimg.com/nb/tw_stock_frontend/scripts/TaChart/tachart.3de240ea9a.html?sid=2330\"   style=\"width: 570px; height: 430px; border-width: 0;\"></iframe>\n");
      out.write("          <iframe id=\"Top5\"  src=\"https://s.yimg.com/nb/tw_stock_frontend/scripts/StxChart/StxChart.9d11dfe155.html?sid=2330\" style=\"width: 560px; height: 380px; border-width: 0;\"></iframe>\n");
      out.write("      </span>\n");
      out.write("  \n");
      out.write("      <form action=\"./check_order.jsp\" method=\"Post\" onsubmit=\"return check_form(this.id);\">\n");
      out.write("      <fieldset name=\"fieldset\">\n");
      out.write("          <legend></legend>\n");
      out.write("          <span>\n");
      out.write("              <button name=\"op1\" id=\"but1\" value=\"1\" type=\"button\" class=\"st_change\" onclick=\"change_border_color(this.id),op1_value(this.id),change_odd(this.id),get_total(this.id)\">證券</button>\n");
      out.write("              <!-- \n");
      out.write("              <button name=\"op1\" id=\"but2\" value=\"2\" type=\"button\" class=\"\" onclick=\"change_border_color(this.id),op1_value(this.id)\" disabled>期貨</button>\n");
      out.write("              <button name=\"op1\" id=\"but3\" value=\"3\" type=\"button\" class=\"\" onclick=\"change_border_color(this.id),op1_value(this.id)\" disabled>選權</button> -->\n");
      out.write("              <button name=\"op1\" id=\"but4\" value=\"0\" type=\"button\" class=\"st_change\" onclick=\"change_border_color(this.id),op1_value(this.id),change_odd(this.id),get_total(this.id)\">零股</button>\n");
      out.write("              <input  name=\"trans_species\" id=\"trans_species\" type=\"hidden\" >\n");
      out.write("              \n");
      out.write("              <label for=\"\">交易帳號:</label>\n");
      out.write("              <select name=\"stock_ID\" id=\"stock_ID\">\n");
      out.write("                  <option value=\"");
      out.print( stock_ID );
      out.write("\" selected>證-");
      out.print( stock_ID );
      out.write("</option>\n");
      out.write("                  <option value=\"一戶多帳號\">期-AAA-BBB-CCC</option>\n");
      out.write("              </select>\n");
      out.write("  \n");
      out.write("              <label for=\"\">標的:</label>\n");
      out.write("              <input type=\"text\" size=\"12\" value=\"顯示公司短稱\">\n");
      out.write("              \n");
      out.write("              <!-- <button class=\"st_lim\">限</button>\n");
      out.write("              <button>漲</button>\n");
      out.write("              <button>跌</button>\n");
      out.write("              <button>平</button>\n");
      out.write("              <button>市</button> -->\n");
      out.write("  \n");
      out.write("              <select name=\"trans_cond\" id=\"trans_cond\" class=\"st_rod\">\n");
      out.write("                  <option value=\"ROD\" selected>ROD</option>\n");
      out.write("                  <option value=\"IOC\">IOC</option>\n");
      out.write("                  <option value=\"FOK\">FOK</option>\n");
      out.write("              </select>\n");
      out.write("              <label for=\"\">單位:</label>\n");
      out.write("              <label id=\"oneorodd\" for=\"\" class=\"forlab\"></label>\n");
      out.write("              <label for=\"\">股</label>\n");
      out.write("              <button name=\"op2\" id=\"1\"  value=\"買進\" type=\"button\" onclick=\"change_back_color(this.id),op2_value(this.id)\" class=\"st_buy st_change\">買進</button>\n");
      out.write("              <button name=\"op2\" id=\"0\"  value=\"賣出\" type=\"button\" onclick=\"change_back_color(this.id),op2_value(this.id)\" class=\"st_sell st_change\">賣出</button>\n");
      out.write("              <input  name=\"trans_sellorbuy\" id=\"trans_sellorbuy\" type=\"hidden\" >\n");
      out.write("          </span>\n");
      out.write("      </fieldset>\n");
      out.write("  \n");
      out.write("      <fieldset name=\"fieldset\">\n");
      out.write("          <legend></legend>\n");
      out.write("              <button name=\"op3\" id=\"but5\" value=\"現股\" type=\"button\" class=\"st_change\" onclick=\"change_border_color(this.id),op3_value(this.id)\">現股</button>\n");
      out.write("              <button name=\"op3\" id=\"but6\" value=\"當沖\" type=\"button\" class=\"st_change\" onclick=\"change_border_color(this.id),op3_value(this.id)\"disabled>當沖</button>\n");
      out.write("              <!--  \n");
      out.write("              <button name=\"op3\" id=\"but7\" value=\"2\" type=\"button\" class=\"st_change\" onclick=\"change_border_color(this.id),op3_value(this.id)\">融資</button>\n");
      out.write("              <button name=\"op3\" id=\"but8\" value=\"3\" type=\"button\" class=\"st_change\" onclick=\"change_border_color(this.id),op3_value(this.id)\">融券</button> -->\n");
      out.write("              <input  name=\"trans_way\" id=\"trans_way\" type=\"hidden\" >\n");
      out.write("              \n");
      out.write("              <label for=\"\" >商品代碼:</label>\n");
      out.write("              <input name=\"com_ID\" type=\"text\" placeholder=\"股票代號\" id=\"com_ID\" autofocus onchange=\"get_input(this.id)\" size=\"17\">\n");
      out.write("              <label for=\"\">價格:</label>\n");
      out.write("              <input name=\"order_price\" id=\"order_price\" type=\"text\" size=\"3\" maxlength=\"7\" onchange=\"get_total(this.id)\">\n");
      out.write("              <label for=\"\">數量:</label>\n");
      out.write("              <input name=\"order_quant\" id=\"order_quant\" type=\"text\" size=\"3\" maxlength=\"4\" onchange=\"get_total(this.id)\">\n");
      out.write("              <label for=\"\" >總價:</label>\n");
      out.write("              <label id=\"show_total\" for=\"\"></label>\n");
      out.write("              <label for=\"\" >新台幣</label>\n");
      out.write("              <input name=\"order_total\" id=\"order_total\" type=\"hidden\" >  \n");
      out.write("              <input type=\"submit\" value=\"立即下單\" class=\"st_submit\" onclick=\"get_datetime()\">\n");
      out.write("              <input type=\"reset\"  value=\"清除\" id=\"clear\" onclick=\"clear()\">\n");
      out.write("              <input name=\"order_date\"   id=\"order_date\"   type=\"hidden\" >\n");
      out.write("              <input name=\"order_time\"   id=\"order_time\"   type=\"hidden\" >\n");
      out.write("              <input name=\"trans_stats\"  id=\"trans_stats\"  type=\"hidden\" value=\"委託單\">\n");
      out.write("            <input name=\"trans_report\" id=\"trans_report\" type=\"hidden\" value=\"委託成功\">            \n");
      out.write("      </fieldset>\n");
      out.write("      </form>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("  \n");
      out.write("      \n");
      out.write("      <div class=\"content\">\n");
      out.write("    \t  <div class=\"header\">即時查詢</div>   \t\n");
      out.write("      \t\t  <iframe src=\"select_order.jsp\" width=\"100%\" frameborder=\"0\"> id=\"select_firame\"></iframe>\n");
      out.write(" \t \t  </div>\n");
      out.write("\t  </div>\n");
      out.write("     \n");
      out.write("     \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"./js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("  <script src=\"./Order.js\" async defer></script>\n");
      out.write("\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
