/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-12 11:31:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean01_3.SocialBean_3;
import java.util.*;
import java.text.SimpleDateFormat;

public final class PostCOL_005f3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean01_3.SocialBean_3");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

response.setContentType("text/html;charset=UTF-8");
response.setHeader("Cache-Control", "no-cache"); // HTTP 1.1
response.setHeader("Pragma", "no-cache"); // HTTP 1.0
response.setDateHeader("Expires", -1); // Prevents caching at the proxy server

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<HTML>\r\n");
      out.write("\r\n");
      out.write("<HEAD>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("  <meta name=\"generator\" content=\"Hugo 0.82.0\">\r\n");
      out.write("  <TITLE>Post_3</TITLE>\r\n");
      out.write("\r\n");
      out.write("  <!-- <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/dashboard/\"> -->\r\n");
      out.write("   <!-- Bootstrap core CSS -->\r\n");
      out.write("   <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"./css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- fontawesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<TITLE>Post_3</TITLE>\r\n");
      out.write("<style>\r\n");
      out.write("\t.bd-placeholder-img {\r\n");
      out.write("      font-size: 1.125rem;\r\n");
      out.write("      text-anchor: middle;\r\n");
      out.write("      -webkit-user-select: none;\r\n");
      out.write("      -moz-user-select: none;\r\n");
      out.write("      user-select: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebarMenu a:hover {\r\n");
      out.write("      color: blue;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (min-width: 768px) {\r\n");
      out.write("      .bd-placeholder-img-lg {\r\n");
      out.write("        font-size: 3.5rem;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("td, th {\r\n");
      out.write("\tborder: 2px solid black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".s1 {\r\n");
      out.write("\twidth: 550px;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".s3 {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".div {\r\n");
      out.write("\tborder: 5px solid black;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tborder-radius: 40px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure {\r\n");
      out.write("\tborder: 3px solid black;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmargin-right: 30px;\r\n");
      out.write("\twidth: 326px;\r\n");
      out.write("\tfont-size: 0.5em;\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tline-height: 1.7;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("\ttext-align: justify;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead {\r\n");
      out.write("\tcolor: brown;\r\n");
      out.write("\ttext-transform: capitalize;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tdocument.createElement(\"article\")\r\n");
      out.write("\tdocument.createElement(\"figure\")\r\n");
      out.write("</script>\r\n");
      out.write("</HEAD>\r\n");
      out.write("\r\n");
      out.write("<BODY >\r\n");
      out.write("\r\n");
      out.write("<header class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\r\n");
      out.write("    <a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3\" href=\"#\">Company name</a>\r\n");
      out.write("    <button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("      data-bs-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <input class=\"form-control form-control-dark w-100\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("    <ul class=\"navbar-nav px-3\">\r\n");
      out.write("      <li class=\"nav-item text-nowrap\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">Sign out</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </header>\r\n");
      out.write("  <div></div>\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\r\n");
      out.write("        <div class=\"position-sticky pt-3\">\r\n");
      out.write("          <ul class=\"nav flex-column\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" aria-current=\"page\" href=\"./dashboard.html\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-tachometer-alt\"></i></span>\r\n");
      out.write("                Dashboard\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./login_1.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-sign-in-alt\"></i></span>\r\n");
      out.write("                會員\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./Login.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-funnel-dollar\"></i></span>\r\n");
      out.write("                下單\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" href=\"./Post_3.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"far fa-comment-dots\"></i></span>\r\n");
      out.write("                討論\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./Buy_4.html\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-dice-d20\"></i></span>\r\n");
      out.write("                抽籤\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./CourseManagement5.html\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-clipboard-list\"></i></span>\r\n");
      out.write("                課程\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"./company_6.jsp\">\r\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-building\"></i></span>\r\n");
      out.write("                公司資料\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      <!-- 內容 -->\r\n");
      out.write("      <main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\">\r\n");
      out.write("\t");
      bean01_3.SocialBean_3 socl_bean = null;
      synchronized (session) {
        socl_bean = (bean01_3.SocialBean_3) _jspx_page_context.getAttribute("socl_bean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (socl_bean == null){
          socl_bean = new bean01_3.SocialBean_3();
          _jspx_page_context.setAttribute("socl_bean", socl_bean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h5>文章編號:0113165</h5>\r\n");
      out.write("\t<H1 ALIGN=\"CENTER\">股市早報</H1>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div></div>\r\n");
      out.write("\t<article class=\"div\">\r\n");
      out.write("\t\t<h2>永豐金拉抬股價</h2>\r\n");
      out.write("\t\t<figure>\r\n");
      out.write("\t\t\t<img src=\"images/永豐金起飛_3.png\" alt=\"\" title=\"挖!\" width=\"300px\">\r\n");
      out.write("\t\t</figure>\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t<p name=\"article\">恭喜今天買永豐金的同學，未來賺錢的機率很高，因為很明顯主力會拉抬股價。\r\n");
      out.write("\t\t\t\t今天在發布之前主力在13.45元掛賣單約1700張，13.5元掛賣單8000多張，13.55元掛賣單2000多張，13.6元掛賣單2000多張，13.65元掛賣單700多張，13.4元掛買單1000多張，只要13.4元買單低於1000張主力很明顯立即補單，也就是主力刻意控制股價在13.4元吃貨，主力意圖非常明顯。\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p name=\"article\">永豐金是一支很棒的股票，尤其今年特別賺錢，金融類股已經悄悄發動了，推薦這支希望能讓大家荷包滿滿。</p>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form action=\"./ProjectServlet_3\" method=\"post\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.print("<font size='24'><b>留言板</b></font>");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"s1\">\r\n");
      out.write("\t\t\t\t<label class=\"s3\" for=\"memo\">留言:</label>\r\n");
      out.write("\t\t\t\t<textarea name=\"comment\" cols=\"50\" rows=\"5\" id=\"memo\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"分享一下吧\"></textarea>\r\n");
      out.write("\t\t\t\t<INPUT NAME=\"INSERT\" TYPE=\"SUBMIT\" VALUE=\"送出\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t    <INPUT NAME=\"SELECTALL\" TYPE=\"SUBMIT\" VALUE=\"展開留言\" id=\"all\"> \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"allfun\">\r\n");
      out.write("\t\t\t\t\t");
 SocialBean_3 bean01= (SocialBean_3)request.getAttribute("qrqr"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					Date date = new Date();
					SimpleDateFormat da = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
					String time = da.format(date);
					
					for(int i=0;i<bean01.getDBcomment_num().size();i++){
      out.write("\r\n");
      out.write("\t\t\t\t    <form action=\"./ProjectServlet_3\" method=\"post\" id=\"form\">\r\n");
      out.write("\t\t\t\t\t     <input type=\"hidden\" name=\"delHidden\" value=\"");
      out.print(bean01.getDBcomment_num().get(i));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t     \r\n");
      out.write(" \t\t\t\t   \t\t <p>");
      out.print(bean01.getDBcomment_num().get(i) );
      out.write("樓:</p>\r\n");
      out.write(" \t\t\t\t   \t\t <br><br><br>\r\n");
      out.write(" \t\t\t\t   \t\t \r\n");
      out.write("\t\t\t\t\t\t <input type=\"text\" name=\"comment_numDB\" value=\"");
      out.print(bean01.getDBcomment_num().get(i) );
      out.write("\" hidden>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t   \t\t <p>留言內容:</p><p id=\"000\">");
      out.print(bean01.getDBcomment().get(i) );
      out.write("</p>\r\n");
      out.write(" \t\t\t\t   \t\t <p><input type=\"text\" id=\"111\"  name=\"commentDB\" value=\"");
      out.print(bean01.getDBcomment().get(i));
      out.write("\">\r\n");
      out.write(" \t\t\t\t   \t\t \r\n");
      out.write(" \t\t\t\t   \t\t <input type=\"submit\" id=\"222\"  value=\"確認修改\" name=\"UPDATE\">\r\n");
      out.write(" \t\t\t\t   \t\t </p><br><br><br>\r\n");
      out.write(" \t\t\t\t  \t\t <p>留言時間:");
      out.print(time);
      out.write("</p>\r\n");
      out.write(" \t\t\t\t  \t\t \r\n");
      out.write(" \t\t\t\t  \t\t <p><input type=\"button\" name=\"\" value=\"修改留言\" id=\"333\">\r\n");
      out.write(" \t\t\t\t  \t\t <input type=\"submit\" name=\"DELETE\" value=\"刪除留言\"></p><hr>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write(" \t\t\t\t  \t\t \r\n");
      out.write(" \t\t\t\t    ");

					   }
 				
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t<!--<table class=\"tb1\">\r\n");
      out.write("  \t\t\t  <thead>\r\n");
      out.write("\t\t\t\t<form action=\"ProjectServlet_3\" method=\"post\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"send\" value=\"a\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"UPDATE\" value=\"修改留言\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"send\" value=\"a\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"DELETE\" value=\"刪除留言\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>-->\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"./js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>$(function(){\r\n");
      out.write("\t\t$('#allfun #111').hide()\r\n");
      out.write("\t\t$('#allfun #222').hide()\r\n");
      out.write("        let i=3\r\n");
      out.write("        $('input#all').on('click',function(){\r\n");
      out.write("            $('div#allfun').append('')\r\n");
      out.write("            i++\r\n");
      out.write("        })\r\n");
      out.write("        $('input#send01').on('click',function(){\r\n");
      out.write("        \tlet a= $('textarea#memo').val()\r\n");
      out.write("        \tif(a===null || a===\"\"){\r\n");
      out.write("        \t\talert(\"你好\")\r\n");
      out.write("        \t\treturn false\r\n");
      out.write("        \t}else{\r\n");
      out.write("        \t\treturn true\r\n");
      out.write("        \t}\r\n");
      out.write("        \t\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$('#allfun #333').on('click',function(){   \r\n");
      out.write("\t\t\t\tlet index = $(this).parent().parent().index()\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tconsole.log(index)\r\n");
      out.write("\t\t\t\t$('#allfun #000').eq(index).toggle()\r\n");
      out.write("\t\t\t\t$('#allfun #111').eq(index).toggle()\r\n");
      out.write("\t\t\t\t$('#allfun #222').eq(index).toggle() \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("        })\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
