/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-12 10:32:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import projectVO_1.ProjectBean;

public final class Update_005finfo_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("projectVO_1.ProjectBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("  <meta name=\"generator\" content=\"Hugo 0.82.0\">\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/dashboard/\"> -->\n");
      out.write("   <!-- Bootstrap core CSS -->\n");
      out.write("   <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"./css/dashboard.css\" rel=\"stylesheet\">\n");
      out.write("  <!-- fontawesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\n");
      out.write("\n");
      out.write("  <style>\n");
      out.write("    .bd-placeholder-img {\n");
      out.write("      font-size: 1.125rem;\n");
      out.write("      text-anchor: middle;\n");
      out.write("      -webkit-user-select: none;\n");
      out.write("      -moz-user-select: none;\n");
      out.write("      user-select: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #sidebarMenu a:hover {\n");
      out.write("      color: blue;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @media (min-width: 768px) {\n");
      out.write("      .bd-placeholder-img-lg {\n");
      out.write("        font-size: 3.5rem;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("<title>會員基本資料</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <header class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\n");
      out.write("    <a class=\"navbar-brand col-md-3 col-lg-2 me-0 px-3\" href=\"#\">Company name</a>\n");
      out.write("    <button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("      data-bs-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <input class=\"form-control form-control-dark w-100\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("    <ul class=\"navbar-nav px-3\">\n");
      out.write("      <li class=\"nav-item text-nowrap\">\n");
      out.write("        <a class=\"nav-link\" href=\"./logout_1.jsp\">Sign out</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("  </header>\n");
      out.write("  <div></div>\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\n");
      out.write("        <div class=\"position-sticky pt-3\">\n");
      out.write("          <ul class=\"nav flex-column\">\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" aria-current=\"page\" href=\"./dashboard.html\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-tachometer-alt\"></i></span>\n");
      out.write("                Dashboard\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link active\" href=\"./login_1.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-sign-in-alt\"></i></span>\n");
      out.write("                會員\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./Login.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-funnel-dollar\"></i></span>\n");
      out.write("                下單\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./Post_3.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"far fa-comment-dots\"></i></span>\n");
      out.write("                討論\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./Buy_4.html\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-dice-d20\"></i></span>\n");
      out.write("                抽籤\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./CourseManagement5.html\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-clipboard-list\"></i></span>\n");
      out.write("                課程\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./company_6.jsp\">\n");
      out.write("                <span class=\"me-1\"><i class=\"fas fa-building\"></i></span>\n");
      out.write("                公司資料\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- 內容 -->\n");
      out.write("      <main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t      ");

	      /* 判斷是否有Login_1.java 執行過後cookie: cookie_id */
	      /* 假如沒有cookie, cookie=null 回到登入畫面 */
	      /* 預設check_id=true 當有cookie_id存在 更改check_id=false */
	      /* 所以當check_id=true 程式就會倒回登入畫面 */
	      Cookie[] cookies = request.getCookies();
	      int i = 0;
	      String string;
	      boolean check_id = true;
	      if (cookies != null) {
	      	for (Cookie c : cookies) {
	      		string = cookies[i].getName();
	      		System.out.println("Update_info_1 cookie check:" + string);
	      		System.out.println("Update_info_1 time:" + i);
	      		i += 1;
	      		if (string.equals("cookie_id")) {
	      	check_id = false;
	      	break;
	      		}
	      	}
	      }
	      if (cookies == null) {
	      	response.sendRedirect("login_1.jsp");
	      	return;
	      }
	      if (check_id) {
	      	response.sendRedirect("login_1.jsp");
	      	return;
	      }
	      
      out.write("\n");
      out.write("\t      \n");
      out.write("\t      ");

	      HttpSession session_1 = request.getSession();
	      ProjectBean bean = (ProjectBean) session_1.getAttribute("member_info");
	      
      out.write("\n");
      out.write("\t\t  <br>\n");
      out.write("          <h1>會員基本資料</h1>\n");
      out.write("          \n");
      out.write("          <form action=\"./Update_info_1\" method=\"post\">\n");
      out.write("            <p>\n");
      out.write("          \t\t帳號：<input type=\"text\" name=\"account_1\" value=\"");
      out.print(bean.getAccount());
      out.write("\"\n");
      out.write("          \t\t\trequired>\n");
      out.write("          \t</p>\n");
      out.write("          \t<p>\n");
      out.write("          \t\t名字：<input type=\"text\" name=\"name_1\" value=\"");
      out.print(bean.getName());
      out.write("\"\n");
      out.write("          \t\t\trequired>\n");
      out.write("          \t</p>\n");
      out.write("          \t<p>\n");
      out.write("          \t\t出生日期：<input type=\"date\" name=\"birthday_1\"\n");
      out.write("          \t\t\tvalue=\"");
      out.print(bean.getBirthday());
      out.write("\">\n");
      out.write("          \t</p>\n");
      out.write("          \t<p>\n");
      out.write("          \t\t別稱：<input type=\"text\" name=\"nickname_1\"\n");
      out.write("          \t\t\tvalue=\"");
      out.print(bean.getNickname());
      out.write("\">\n");
      out.write("          \t</p>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("            \t性別：\n");
      out.write("            \t<label for=\"male\">男性</label> \n");
      out.write("            \t<input type=\"radio\"\n");
      out.write("            \t\tname=\"gender_1\" id=\"male\" value=\"male\" required>\n");
      out.write("            \n");
      out.write("           \n");
      out.write("            \t<label for=\"female\">女性</label> \n");
      out.write("            \t<input type=\"radio\"\n");
      out.write("            \t\tname=\"gender_1\" id=\"female\" value=\"female\" required>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \t<label for=\"other\">其他</label>\n");
      out.write("            \t <input type=\"radio\"\n");
      out.write("            \t\tname=\"gender_1\" id=\"other\" value=\"other\" required>\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("            \t電子信箱：<input type=\"email\" name=\"email_1\" value=\"");
      out.print(bean.getE_mail());
      out.write("\"\n");
      out.write("            \t\trequired>\n");
      out.write("            </p>\n");
      out.write("            <p>\n");
      out.write("            \t手機：<input type=\"text\" name=\"cellphone_1\" value=\"");
      out.print(bean.getCellphone());
      out.write("\">\n");
      out.write("            </p>\n");
      out.write("            <p>\n");
      out.write("            \t地址：<input type=\"text\" name=\"address_1\" value=\"");
      out.print(bean.getAddress());
      out.write("\">\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <label for=\"job\">職業：</label> \n");
      out.write("            <select name=\"job_1\" id=\"job\">\n");
      out.write("            \t<option value=\"農牧業\">農牧業</option>\n");
      out.write("            \t<option value=\"漁業\">漁業</option>\n");
      out.write("            \t<option value=\"木材森林業\">木材森林業</option>\n");
      out.write("            \t<option value=\"礦業採石業\">礦業採石業</option>\n");
      out.write("            \t<option value=\"交通運輸業\">交通運輸業</option>\n");
      out.write("            \t<option value=\"餐旅業\">餐旅業</option>\n");
      out.write("            \t<option value=\"建築工程業\">建築工程業</option>\n");
      out.write("            \t<option value=\"製造業\">製造業</option>\n");
      out.write("            \t<option value=\"新聞廣告業\">新聞廣告業</option>\n");
      out.write("            \t<option value=\"衛生保健\">衛生保健</option>\n");
      out.write("            \t<option value=\"娛樂業\">娛樂業</option>\n");
      out.write("            \t<option value=\"文教機關\">文教機關</option>\n");
      out.write("            \t<option value=\"宗教團體\">宗教團體</option>\n");
      out.write("            \t<option value=\"公共事業\">公共事業</option>\n");
      out.write("            \t<option value=\"一般商業\">一般商業</option>\n");
      out.write("            \t<option value=\"服務業\">服務業</option>\n");
      out.write("            \t<option value=\"家庭管理\">家庭管理</option>\n");
      out.write("            \t<option value=\"資訊業\">資訊業</option>\n");
      out.write("            \t<option value=\"治安人員\">治安人員</option>\n");
      out.write("            \t<option value=\"軍人\">軍人</option>\n");
      out.write("            \t<option value=\"運動人員\">運動人員</option>\n");
      out.write("            \t<option value=\"學生\">學生</option>\n");
      out.write("            \t<option value=\"其他\">其他</option>\n");
      out.write("            </select>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("            \t載具：<input type=\"text\" name=\"carrier_1\" value=\"");
      out.print(bean.getCarrier());
      out.write("\">\n");
      out.write("            </p>\n");
      out.write("            <input type=\"submit\" value=\"更改\">\n");
      out.write("            \n");
      out.write("            <!-- 看是否有錯誤訊息由後端傳入 -->\t\t\n");
      out.write("\t\t    ");

		    String str = (String) request.getAttribute("message");
		    if (str != null) {
      out.write("\n");
      out.write("\t\t    \n");
      out.write("\t\t    <p style=\"color: crimson;\">\n");
      out.write("\t\t    \t");
      out.print( str);
      out.write("\n");
      out.write("\t\t    </p>\n");
      out.write("\t\t    \n");
      out.write("\t\t    ");
}
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t  </form>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("      </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"./js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t$(\"#");
      out.print(bean.getGender());
      out.write("\").prop('checked', true)\n");
      out.write("\t\t\t$(\"#job\").val(\"");
      out.print(bean.getJob());
      out.write("\");\n");
      out.write("\t\t})\t\n");
      out.write("  </script>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
